#!/bin/csh

set STARLIB = SL21d
set SRC = "src"
set INC = "include"
set DEST = "StRoot/StUPCFilterMaker"
set TMP = "tmp"

set srclist= ( StUPCBemcCluster StUPCEvent StUPCFilterMaker StUPCFilterBemcUtil StUPCFilterTrgUtil StUPCTrack StUPCVertex StUPCTofHit StRPEvent StUPCRpsTrack StUPCRpsTrackPoint StUPCRpsCluster StUPCFilterRPUtil ) 

mkdir -p $DEST

foreach file ( ${srclist} )

  cp -f $SRC"/"$file.cxx $DEST/
  cp -f $INC"/"$file.h $DEST/
end


#TOF calib maker with start time override
mkdir $TMP; cd $TMP
git clone --branch ${STARLIB} --filter=blob:none --no-checkout  https://github.com/star-bnl/star-sw.git
cd star-sw
git config core.sparseCheckout true
git config core.sparseCheckoutCone true
git sparse-checkout set StRoot/StBTofCalibMaker
cd ..
mv star-sw/StRoot/StBTofCalibMaker ../StRoot/
cd ..
rm -rf $TMP

starver $STARLIB

cons
